const DAY_MS = 24 * 60 * 60 * 1000;

/**
 * Deterministically compute attendance intelligence signals from raw attendance
 * records (expects a 30-day lookback window, each row shaped like:
 * { employee_id, date, status, employees: { first_name, last_name, department } }).
 *
 * These numbers feed HR decisions and DOLE-adjacent flags, so they are computed
 * directly from the data - never inferred or generated by an LLM. Gemini's job
 * (see geminiBrain.js `narrateAttendanceHealth`) is only to phrase a short summary
 * on top of these already-correct figures, never to produce the figures themselves.
 */
export function computeAttendanceSignals(records) {
    const byEmployee = {};

    (records || []).forEach(r => {
        const empId = r.employee_id;
        if (!empId) return;
        if (!byEmployee[empId]) {
            byEmployee[empId] = {
                employee_id: empId,
                name: r.employees ? `${r.employees.first_name || ''} ${r.employees.last_name || ''}`.trim() || String(empId) : String(empId),
                department: r.employees?.department || 'General',
                dates: [],
                lateCount: 0,
                // Sun..Sat histogram, used for the Monday/Friday absenteeism heuristic
                dowCounts: [0, 0, 0, 0, 0, 0, 0]
            };
        }
        const e = byEmployee[empId];
        e.dates.push(r.date);
        if ((r.status || '').toLowerCase().includes('late')) e.lateCount += 1;
        const dow = new Date(r.date + 'T00:00:00').getDay();
        e.dowCounts[dow] += 1;
    });

    const employees = Object.values(byEmployee);

    // Longest consecutive-worked-day streak per employee - same rule the DOLE
    // rest-day compliance check uses (Labor Code Art. 91: 1 rest day per 6 work days).
    employees.forEach(e => {
        e.totalDays = e.dates.length;
        const sorted = [...new Set(e.dates)].sort();
        let streak = 1;
        let max = 1;
        for (let i = 1; i < sorted.length; i++) {
            const diff = Math.round((new Date(sorted[i]) - new Date(sorted[i - 1])) / DAY_MS);
            streak = diff === 1 ? streak + 1 : 1;
            max = Math.max(max, streak);
        }
        e.longestStreak = max;
    });

    const frequent_late_patterns = employees
        .filter(e => e.lateCount >= 3)
        .map(e => ({
            employee_id: e.employee_id,
            employee_name: e.name,
            department: e.department,
            late_count: e.lateCount,
            severity: e.lateCount >= 8 ? 'High' : e.lateCount >= 5 ? 'Medium' : 'Low',
            insight: `${e.lateCount} late arrivals in the last 30 days`
        }))
        .sort((a, b) => b.late_count - a.late_count)
        .slice(0, 10);

    const burnout_risk_alerts = employees
        .filter(e => e.longestStreak >= 7)
        .map(e => ({
            employee_id: e.employee_id,
            employee_name: e.name,
            department: e.department,
            consecutive_days: e.longestStreak,
            reason: `Worked ${e.longestStreak} consecutive days without a rest day`,
            suggested_action: e.longestStreak >= 12
                ? 'Mandate an immediate rest day - this significantly exceeds Labor Code Art. 91'
                : 'Schedule a rest day within the next cycle to stay Art. 91 compliant'
        }))
        .sort((a, b) => b.consecutive_days - a.consecutive_days)
        .slice(0, 10);

    // Monday/Friday absenteeism proxy: compare Mon/Fri clock-in frequency against the
    // employee's own Tue/Wed/Thu/Sat baseline (6-day work week per the DOLE rules above).
    // Only flagged with a reasonable sample size to avoid noise on short histories.
    const monday_friday_patterns = employees
        .filter(e => e.totalDays >= 8)
        .map(e => {
            const baseline = (e.dowCounts[2] + e.dowCounts[3] + e.dowCounts[4] + e.dowCounts[6]) / 4;
            if (baseline < 1) return null;
            const mondayRatio = e.dowCounts[1] / baseline;
            const fridayRatio = e.dowCounts[5] / baseline;
            if (mondayRatio <= 0.5) {
                return { employee_id: e.employee_id, employee_name: e.name, pattern: 'Noticeably fewer Monday clock-ins vs. rest of the week' };
            }
            if (fridayRatio <= 0.5) {
                return { employee_id: e.employee_id, employee_name: e.name, pattern: 'Noticeably fewer Friday clock-ins vs. rest of the week' };
            }
            return null;
        })
        .filter(Boolean)
        .slice(0, 10);

    return {
        anomalies_detected_count: frequent_late_patterns.length + burnout_risk_alerts.length + monday_friday_patterns.length,
        frequent_late_patterns,
        burnout_risk_alerts,
        monday_friday_patterns,
        sample_size: employees.length
    };
}
